name: 'VS Code to Visual Studio Theme Converter'
description:
  'A GitHub Action that converts a Visual Studio Code theme to a Visual Studio
  theme.'
author: 'Alex Ravenna'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'heart'
  color: 'red'

# Define your inputs here.
inputs:
  path:
    description: 'The path to the VS Code theme JSON to be converted'
    required: false
    default: 'theme.json'

# Define your outputs here.
outputs:
  output-vsix:
    description: 'The path to the output VSIX file'

runs:
  using: node20
  main: dist/index.js
